#!/bin/bash
set -euo pipefail
# need to erase pids, locks, etc.
rm -rf '/tmp/apache2'
mkdir -m 700 '/tmp/apache2'
export APACHE_CONFDIR=/etc/apache2
export APACHE_ENVVARS=$APACHE_CONFDIR/envvars
source "$APACHE_ENVVARS"
apache2 -t
exec apache2 -DFOREGROUND
