#!/bin/bash
set -eu -o pipefail
rm -f /etc/postgrey/postgrey_whitelist_clients
cp /usr/share/postgrey/postgrey_whitelist_clients /etc/postgrey/postgrey_whitelist_clients
cd '/srv/postgrey/db'
exec /usr/sbin/postgrey \
    --daemonize \
    --dbdir '/srv/postgrey/db' \
    --group="$(id -g -n)" \
    --inet=127.0.0.1:10023 \
    --pidfile '/run/postgrey/postgrey.pid' \
    --syslog-facility=mail \
    --user="$USER"
