#!/bin/bash
#
# Usage: run [bash -l]
#
set -euo pipefail
# Needed to allow for empty commands (e.g. docker_registry), bash will complain
# if an variable is empty as unbound (set -u above)
image_cmd=( 'docker.io/radiasoft/wordpress:dev' )
user=vagrant
if (( $# > 0 )); then
    # No name if called on the command line; called from command line so default log driver
    flags=( -i )
    if [[ -t 0 ]]; then
        # probably interactive debugging so allow strace
        flags+=( -t --cap-add SYS_PTRACE )
    fi
    cmd=( /srv/wordpress/cmd )
    if [[ ${cmd[@]} ]]; then
        image_cmd+=( "${cmd[@]}" )
    fi
    image_cmd+=( "$@" )
    if [[ ${start_run_u:=} ]]; then
        user=$start_run_u
    fi
else
    # Systemd logs output to journal so we don't need docker to log, too.
    # No core dumps in daemons
    flags=( --name "wordpress"  --log-driver=none --ulimit core=0 )
    image_cmd+=( /srv/wordpress/cmd )
fi
# --init runs tini wrapper: https://github.com/krallin/tini
exec docker run "${flags[@]}" --init --rm "--user=$user" --network=host -v '/srv/wordpress:/srv/wordpress' -v '/srv/wordpress/apache.conf:/etc/apache2/sites-enabled/000-default.conf' -v '/srv/wordpress/envvars:/etc/apache2/envvars'  "${image_cmd[@]}"
