#!/bin/bash
devbox_devtech3_rsconf_component() {
rsconf_service_prepare 'devbox_devtech3' '/etc/systemd/system/devbox_devtech3.service' '/etc/systemd/system/devbox_devtech3.service.d' '/srv/devbox_devtech3' '/srv/devbox_devtech3/sshd'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3'
rsconf_install_access '500' 'vagrant' 'vagrant'
rsconf_install_file '/srv/devbox_devtech3/cmd' 'e4519a71f8e5f1ccf0006350977c367d'
rsconf_install_file '/srv/devbox_devtech3/env' '22e03a134cc868bb12094d8dc118a6c4'
rsconf_install_file '/srv/devbox_devtech3/remove' 'd8d61104199236b9701424db5247cc32'
rsconf_install_file '/srv/devbox_devtech3/start' '2f38a72aa54c92da90ff5ebe49149a8d'
rsconf_install_file '/srv/devbox_devtech3/stop' '38bd86d43d98dfac2ccce1feca46f21c'
rsconf_install_access '444' 'root' 'root'
rsconf_install_file '/etc/systemd/system/devbox_devtech3.service' 'afdbd1365adaa419c07b302e20dff287'
rsconf_service_docker_pull 'v3.radia.run:5000/radiasoft/beamsim-jupyter:dev' 'devbox_devtech3'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3/jupyter'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3/src'
rsconf_install_directory '/srv/devbox_devtech3/src/biviosoftware'
rsconf_install_directory '/srv/devbox_devtech3/src/biviosoftware/home-env'
rsconf_clone_repo https://github.com/biviosoftware/home-env.git /srv/devbox_devtech3/src/biviosoftware/home-env vagrant
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3/sshd'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3'
rsconf_install_access '600' 'vagrant' 'vagrant'
rsconf_install_ensure_file_exists '/srv/devbox_devtech3/jupyter/bashrc'
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_FEATURE_CONFIG_PACKAGE_PATH=\'sirepo\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_FEATURE_CONFIG_SIM_TYPES=\'elegant:srw\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_PKCLI_SERVICE_PORT=\'3200\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_PKCLI_JOB_SUPERVISOR_PORT=\'3300\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_JOB_DRIVER_LOCAL_SUPERVISOR_URI=\'http://127.0.0.1:3300\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_JOB_API_SUPERVISOR_URI=\'http://127.0.0.1:3300\''
rsconf_install_access '400' 'vagrant' 'vagrant'
rsconf_install_file '/srv/devbox_devtech3/sshd/sshd_config' 'f0bee61432e3efc4e89a8414cff96f80'
rsconf_install_file '/srv/devbox_devtech3/sshd/host_key' '40d0ed69bc1d2e3e638e0ac2ab86befe'
rsconf_install_file '/srv/devbox_devtech3/sshd/identity.pub' 'c11707cc9925ab0f91e9caedefebb005'
}
