#!/bin/bash
if [[ -r ~/.bashrc ]]; then
    source ~/.bashrc
fi
set -euo pipefail
cd '/srv/mpi_worker'
source ./env
if [[ $@ ]]; then
    exec "$@"
fi
exec /usr/sbin/sshd -D -f '/home/vagrant/jupyter/.rsmpi/v6.radia.run/sshd_config'
