#!/bin/bash
set -eou pipefail

_static_files_gen_prog=$0

static_files_gen_do() {
    declare nginx_d=$1
    # POSIT: mounted inside the container and writable
    declare d='/srv/sirepo/static_files_gen_tmp'
    rm -rf "$d"
    install -o 'vagrant' -d "$d"
    /srv/sirepo/start sirepo static_files gen "$d"
    chown -R vagrant: "$d"
    find "$d" -type d -print0 | xargs -0 chmod 711
    find "$d" -type f -print0 | xargs -0 chmod 444
    static_files_gen_mv "$nginx_d" "$d"
}

static_files_gen_main() {
    declare nginx_d='/srv/www/sirepo'
    if static_files_gen_needed "$nginx_d"; then
        echo "Generating: $nginx_d" 1>&2
        static_files_gen_do "$nginx_d"
    fi
}

static_files_gen_mv() {
    declare nginx_d=$1
    declare gen_d=$2
    declare t=$nginx_d.tmp
    declare o=$nginx_d.old
    rm -rf "$t" "$o"
    # Move to same file system so the move in place are fast and atomic
    mv "$d" "$t"
    if [[ -e $nginx_d ]]; then
        mv "$nginx_d" "$o"
    fi
    mv "$t" "$nginx_d"
    rm -rf "$o"
}

static_files_gen_needed() {
    declare nginx_d=$1
    if [[ ${static_files_gen_force:+1} || ! -d $nginx_d ]]; then
        return 0
    fi
    [[ $(find "$nginx_d" -type f -newer "$_static_files_gen_prog" -print -quit) ]]
}

static_files_gen_main "$@"
