#!/bin/bash
set -eu -o pipefail
docker exec -i 'wordpress' bash <<'EOF'
set -eu -o pipefail
export APACHE_CONFDIR=/etc/apache2
export APACHE_ENVVARS=$APACHE_CONFDIR/envvars
source "$APACHE_ENVVARS"
apache2 -t
apache2 -k graceful
EOF
