#!/bin/bash
devbox_fullstackdude_rsconf_component() {
rsconf_service_prepare 'devbox_fullstackdude' '/etc/systemd/system/devbox_fullstackdude.service' '/etc/systemd/system/devbox_fullstackdude.service.d' '/srv/devbox_fullstackdude' '/srv/devbox_fullstackdude/sshd'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_fullstackdude'
rsconf_install_access '500' 'vagrant' 'vagrant'
rsconf_install_file '/srv/devbox_fullstackdude/cmd' '7303e61dd1dd1c35b04db8d1c4a1c013'
rsconf_install_file '/srv/devbox_fullstackdude/env' '22e03a134cc868bb12094d8dc118a6c4'
rsconf_install_file '/srv/devbox_fullstackdude/remove' '6bd04616c98ad5b8a6c51ed243001c78'
rsconf_install_file '/srv/devbox_fullstackdude/start' '506cca4b3e984ee51359a99ad0c3a684'
rsconf_install_file '/srv/devbox_fullstackdude/stop' 'fd291f004de34c8c32dedffa727e0788'
rsconf_install_access '444' 'root' 'root'
rsconf_install_file '/etc/systemd/system/devbox_fullstackdude.service' '9cfe600b295c2da113f8c6ab4dad7280'
rsconf_service_docker_pull 'v3.radia.run:5000/radiasoft/beamsim-jupyter:dev' 'devbox_fullstackdude'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_fullstackdude/jupyter'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_fullstackdude/src'
rsconf_install_directory '/srv/devbox_fullstackdude/src/biviosoftware'
rsconf_install_directory '/srv/devbox_fullstackdude/src/biviosoftware/home-env'
rsconf_clone_repo https://github.com/biviosoftware/home-env.git /srv/devbox_fullstackdude/src/biviosoftware/home-env vagrant
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_fullstackdude/sshd'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_fullstackdude'
rsconf_install_access '600' 'vagrant' 'vagrant'
rsconf_install_ensure_file_exists '/srv/devbox_fullstackdude/jupyter/bashrc'
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_fullstackdude/jupyter/bashrc' $'export SIREPO_FEATURE_CONFIG_PACKAGE_PATH=\'sirepo\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_fullstackdude/jupyter/bashrc' $'export SIREPO_FEATURE_CONFIG_SIM_TYPES=\'elegant:srw\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_fullstackdude/jupyter/bashrc' $'export SIREPO_PKCLI_SERVICE_PORT=\'3201\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_fullstackdude/jupyter/bashrc' $'export SIREPO_PKCLI_JOB_SUPERVISOR_PORT=\'3301\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_fullstackdude/jupyter/bashrc' $'export SIREPO_JOB_DRIVER_LOCAL_SUPERVISOR_URI=\'http://127.0.0.1:3301\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_fullstackdude/jupyter/bashrc' $'export SIREPO_JOB_API_SUPERVISOR_URI=\'http://127.0.0.1:3301\''
rsconf_install_access '400' 'vagrant' 'vagrant'
rsconf_install_file '/srv/devbox_fullstackdude/sshd/sshd_config' '179121469e4dd3aed49a05c979f6c26b'
rsconf_install_file '/srv/devbox_fullstackdude/sshd/host_key' '51239a03b3421de7b20b9fb5f8c0f632'
rsconf_install_file '/srv/devbox_fullstackdude/sshd/identity.pub' 'c3d2bac784399f08153d897c5d38dd84'
}
