#!/bin/bash
devbox_devtech3_rsconf_component() {
rsconf_service_prepare 'devbox_devtech3' '/etc/systemd/system/devbox_devtech3.service' '/etc/systemd/system/devbox_devtech3.service.d' '/srv/devbox_devtech3' '/srv/devbox_devtech3/sshd'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3'
rsconf_install_access '500' 'vagrant' 'vagrant'
rsconf_install_file '/srv/devbox_devtech3/cmd' '8e466ca4d3b55a44cfdb0a9721db82cd'
rsconf_install_file '/srv/devbox_devtech3/env' '22e03a134cc868bb12094d8dc118a6c4'
rsconf_install_file '/srv/devbox_devtech3/remove' '0d858f484cd79600d2fe2e62ac09b85c'
rsconf_install_file '/srv/devbox_devtech3/start' '0eee894d1ddb6545bd50573e5a2c19e4'
rsconf_install_file '/srv/devbox_devtech3/stop' '91ce64afd45dcf8edf13e2e4b2e2269b'
rsconf_install_access '444' 'root' 'root'
rsconf_install_file '/etc/systemd/system/devbox_devtech3.service' '5fcc2fb10b69bb6fc0ee2b5d83dec73c'
rsconf_service_docker_pull 'v3.radia.run:5000/radiasoft/beamsim-jupyter:dev' 'devbox_devtech3'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3/jupyter'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3/src'
rsconf_install_directory '/srv/devbox_devtech3/src/biviosoftware'
rsconf_install_directory '/srv/devbox_devtech3/src/biviosoftware/home-env'
rsconf_clone_repo https://github.com/biviosoftware/home-env.git /srv/devbox_devtech3/src/biviosoftware/home-env vagrant
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3/sshd'
rsconf_install_access '700' 'vagrant' 'vagrant'
rsconf_install_directory '/srv/devbox_devtech3'
rsconf_install_access '600' 'vagrant' 'vagrant'
rsconf_install_ensure_file_exists '/srv/devbox_devtech3/jupyter/bashrc'
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_FEATURE_CONFIG_PACKAGE_PATH=\'sirepo\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_FEATURE_CONFIG_SIM_TYPES=\'elegant:srw\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_PKCLI_SERVICE_PORT=\'3200\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_PKCLI_JOB_SUPERVISOR_PORT=\'3300\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_JOB_DRIVER_LOCAL_SUPERVISOR_URI=\'http://127.0.0.1:3300\''
rsconf_edit_no_change_res=0 rsconf_append $'/srv/devbox_devtech3/jupyter/bashrc' $'export SIREPO_JOB_API_SUPERVISOR_URI=\'http://127.0.0.1:3300\''
rsconf_install_access '400' 'vagrant' 'vagrant'
rsconf_install_file '/srv/devbox_devtech3/sshd/sshd_config' 'cf67e0db642e9bafb479c7b0c70f1495'
rsconf_install_file '/srv/devbox_devtech3/sshd/host_key' '40d0ed69bc1d2e3e638e0ac2ab86befe'
rsconf_install_file '/srv/devbox_devtech3/sshd/identity.pub' 'c11707cc9925ab0f91e9caedefebb005'
}
