#!/bin/bash
set -euo pipefail
# Avoid filling up log so can see output of backup more clearly
pip --quiet --disable-pip-version-check install 'git+git://github.com/radiasoft/pykern#egg=pykern'
# https://git-scm.com/docs/git-credential-store#_storage_format
install -m 600 /dev/stdin ~/.github_bkp_creds <<EOF
https://$PYKERN_PKCLI_GITHUB_USER:$PYKERN_PKCLI_GITHUB_PASSWORD@github.com
EOF
git config --global credential.helper "store --file $HOME/.github_bkp_creds"
cd /srv/github_bkp/db
exec pykern github backup
