#!/bin/bash
#
# Usage: run [bash -l]
#
set -euo pipefail
# Needed to allow for empty commands (e.g. docker_registry), bash will complain
# if an variable is empty as unbound (set -u above)
image_cmd=( 'radiasoft/mariadb:latest' )
user=vagrant
if (( $# > 0 )); then
    # No name if called on the command line; called from command line so default log driver
    flags=( -i )
    if [[ -t 0 ]]; then
        # probably interactive debugging so allow strace
        flags+=( -t --cap-add SYS_PTRACE )
    fi
    image_cmd+=( /srv/rs_mariadb/cmd )
    image_cmd+=( "$@" )
    if [[ ${start_run_u:=} ]]; then
        user=$start_run_u
    fi
else
    # Systemd logs output to journal so we don't need docker to log, too.
    # No core dumps in daemons
    flags=( --name "rs_mariadb"  --log-driver=none --ulimit core=0 )
    image_cmd+=( /srv/rs_mariadb/cmd )
fi
# --init runs tini wrapper: https://github.com/krallin/tini
exec docker run "${flags[@]}" --init --rm "--user=$user" --network=host -v '/srv/rs_mariadb:/srv/rs_mariadb' -v '/srv/rs_mariadb/my.cnf:/etc/my.cnf' -v '/srv/rs_mariadb/db:/var/lib/mysql'  "${image_cmd[@]}"
